const Images = {
    // global icons
    leftArrowIcon:"/assets/images/global/leftArrowIcon.png",
    logoIcon : "/assets/images/Landing/logo.png",
    plusWhiteIcon:"/assets/images/global/plusWhiteIcon.png",

    // landing
    logo : "/assets/images/Landing/logo.png",
    novaapp : "/assets/images/Landing/novaapp.png",
    playstore : "/assets/images/Landing/playstore.png",
    appstore : "/assets/images/Landing/appstore.png",
    coverimg: "/assets/images/Landing/coverimage.png",
    profile: "/assets/images/Landing/profile.png",
    profile1: "/assets/images/Landing/profile1.png",
    profile2: "/assets/images/Landing/profile2.png",
    profile3: "/assets/images/Landing/profile3.png",
    arrow: "/assets/images/Landing/arrow.png",
    king: "/assets/images/Landing/king.png",

    // sidebaricon
    profileicon: "/assets/images/sidebarIcon/profileicon.png",
    search: "/assets/images/sidebarIcon/search.png",
    connect: "/assets/images/sidebarIcon/connect.png",
    market: "/assets/images/sidebarIcon/market.png",
    creativehub: "/assets/images/sidebarIcon/creativehub.png",
    communityhub: "/assets/images/sidebarIcon/communityhub.png",
    maps: "/assets/images/sidebarIcon/maps.png",
    createicon: "/assets/images/sidebarIcon/create.png",
    dmsIcon: "/assets/images/sidebarIcon/dmsIcon.png",

    // connect
    dms: "/assets/images/Landing/dms.png",
    chat: "/assets/images/Landing/chat.png",
    channel: "/assets/images/Landing/channel.png",
    creator1: "/assets/images/Landing/creatorimg1.png",
    creator2: "/assets/images/Landing/creatorimg2.png",
    settingIcon:"/assets/images/connect/settings.png",
    chatBotIcon:"/assets/images/connect/chatBotIcon.png",
    reelLikeIcon:"/assets/images/connect/reelLikeIcon.png",
    reelCommentIcon:"/assets/images/connect/reelCommentIcon.png",
    reelLiveIcon:"/assets/images/connect/reelLiveIcon.png",
    reelMoreIcon:"/assets/images/connect/reelMoreIcon.png",
    reelSaveIcon:"/assets/images/connect/reelSaveIcon.png",
    reelShareIcon:"/assets/images/connect/reelShareIcon.png",
    searchIcon:"/assets/images/connect/searchIcon.png",
    chatProfile:"/assets/images/connect/chatProfile.png",
    camaraIcon:"/assets/images/connect/camaraIcon.png",
    videoCallIcon:"/assets/images/connect/videoCallIcon.png",
    callIcon:"/assets/images/connect/callIcon.png",
    camaraBlackIcon:"/assets/images/connect/camaraBlackIcon.png",
    stickerIcon:"/assets/images/connect/stickerIcon.png",
    micIcon:"/assets/images/connect/micIcon.png",
    galleryIcon:"/assets/images/connect/galleryIcon.png",
    audioPlayIcon:"/assets/images/connect/audioPlayIcon.png",
    chatMsgProfile:"/assets/images/connect/chatMsgProfile.png",
    
    //community hub 
    communityHubSearchIcon:"/assets/images/communityHub/searchIcon.png",
    communityhubPostImage:"/assets/images/communityHub/postImageIcon.png",
    dollerIcon:"/assets/images/communityHub/dollerIcon.png",
    channelProfileImage:"/assets/images/communityHub/channelProfileImage.png",
    userIcon:"/assets/images/communityHub/userIcon.png",
    communitySettingIcon:"/assets/images/communityHub/settingIcon.png",
    galleryImg1:"/assets/images/communityHub/galleryImg1.png",
    galleryImg2:"/assets/images/communityHub/galleryImg2.png",
    galleryImg3:"/assets/images/communityHub/galleryImg3.png",
    chatCardIcon:"/assets/images/communityHub/chatCardIcon.png",
    groupChatIcon:"/assets/images/communityHub/groupChatIcon.png",
    searchCardIcon:"/assets/images/communityHub/searchCardIcon.png",
    deleteIcon:"/assets/images/communityHub/deleteIcon.png",
    copyIcon:"/assets/images/communityHub/copyIcon.png",
    bannerImg:"/assets/images/communityHub/bannerImg.png",
    addChatIcon:"/assets/images/communityHub/addChatIcon.png",
    addTaskIcon:"/assets/images/communityHub/addTaskIcon.png",
    mediaIcon:"/assets/images/communityHub/mediaIcon.png",
    mediaIcon:"/assets/images/communityHub/mediaIcon.png",
    memberSearchIcon:"/assets/images/communityHub/memberSearchIcon.png",
    starIcon:"/assets/images/communityHub/starIcon.png",
    pinedIcon:"/assets/images/communityHub/pinIcon.png",
    rightArrowIcon:"/assets/images/communityHub/rightArrowIcon.png",
    plusIcon:"/assets/images/communityHub/plusIcon.png",
    rightArrowMarkIcon:"/assets/images/communityHub/rightArrowMark.png",
    
    // post
    postImg:"/assets/images/post/postImg.png",
    likeIcon:"/assets/images/post/likedIcon.png",
    commentIcon:"/assets/images/post/commentIcon.png",
    shareIcon:"/assets/images/post/shareIcon.png",
    unSavedIcon:"/assets/images/post/unSavedIcon.png",
    savedIcon:"/assets/images/post/savedIcon.png",
    timeIcon:"/assets/images/post/timeIcon.png",
    commentLikeIcon:"/assets/images/post/commentLikeIcon.png",
    emojiIcon:"/assets/images/post/emojiIcon.png",
    userProfileIcon:"/assets/images/post/userProfileIcon.png",
    postmoreIcon:"/assets/images/communityHub/moreIcon.png",
    
    //Creator Hub
    creatorCardImage:"/assets/images/creativehub/cardImage.png",
    pollsCardIcon:"/assets/images/creativehub/pollsIcon.png",
    reelsCardIcon:"/assets/images/creativehub/reelsIcon.png",
    organizationImg1:"/assets/images/creativehub/organizationImg1.png",
    organizationImg2:"/assets/images/creativehub/organizationImg2.png",
    liveStreamIcon:"/assets/images/creativehub/LiveStreamIcon.png",
    coachingIcon:"/assets/images/creativehub/coachingIcon.png",
    onlineCourseIcon:"/assets/images/creativehub/onlineCourseIcon.png",
    discoverOrg1:"/assets/images/creativehub/discoverOrg1.png",
    discoverOrg2:"/assets/images/creativehub/discoverOrg2.png",
    profileOptionIcon:"/assets/images/creativehub/profileOptionIcon.png",
    sendIcon:"/assets/images/creativehub/sendIcon.png",
    callIcon:"/assets/images/creativehub/callIcon.png",
    videoCallIcon:"/assets/images/creativehub/videoCallIcon.png",
    instagramIcon:"/assets/images/creativehub/instagramIcon.png",
    faceBookIcon:"/assets/images/creativehub/faceBookIcon.png",
    networkIcon:"/assets/images/creativehub/networkIcon.png",
    profileUserImg:"/assets/images/creativehub/profileImg.png",
    profileBannerImg:"/assets/images/creativehub/bannerImg.png",
    creatorStudioImg1:"/assets/images/creativehub/creatorStudioImg1.png",
    creatorStudioImg2:"/assets/images/creativehub/creatorStudioImg2.png",
    creatorStudioImg3:"/assets/images/creativehub/creatorStudioImg3.png",
    creatorStudioImg4:"/assets/images/creativehub/creatorStudioImg4.png",
    creatorStudioImg5:"/assets/images/creativehub/creatorStudioImg5.png",
    creatorStudioImg6:"/assets/images/creativehub/creatorStudioImg6.png",
    creatorStudioImg7:"/assets/images/creativehub/creatorStudioImg7.png",
    creatorStudioImg8:"/assets/images/creativehub/creatorStudioImg8.png",
    creatorStudioImg9:"/assets/images/creativehub/creatorStudioImg9.png",
    creatorStudioImg10:"/assets/images/creativehub/creatorStudioImg10.png",
    postIcon:"/assets/images/creativehub/postIcon.png",
    pinIcon:"/assets/images/creativehub/pinIcon.png",
    privateIcon:"/assets/images/creativehub/privateIcon.png",
    postImg1:"/assets/images/creativehub/postImg1.png",
    postImg2:"/assets/images/creativehub/postImg2.png",
    postImg3:"/assets/images/creativehub/postImg3.png",
    postImg4:"/assets/images/creativehub/postImg4.png",
    postImg5:"/assets/images/creativehub/postImg5.png",
    postImg6:"/assets/images/creativehub/postImg6.png",
    
    //profile
    followIcon:"/assets/images/profile/followIcon.png",
    donateIcon:"/assets/images/profile/donateIcon.png",
    addPassIcon:"/assets/images/profile/addPassIcon.png",
    passTicketIcon:"/assets/images/profile/passTicketIcon.png",
    passArrowIcon:"/assets/images/profile/passArrowIcon.png",
    
    // create post
    postPreview:"/assets/images/createPost/imgPreviewImg.png",
    postGalleryIcon:"/assets/images/createPost/galleryIcon.png",
    addTextIcon:"/assets/images/createPost/addTextIcon.png",
    effectIcon:"/assets/images/createPost/effectIcon.png",
    filterIcon:"/assets/images/createPost/filterIcon.png",
    addMusicIcon:"/assets/images/createPost/addMusicIcon.png",
    createPassIcon:"/assets/images/createPost/addPassIcon.png",
    locationIcon:"/assets/images/createPost/locationIcon.png",
    replyIcon:"/assets/images/createPost/replyIcon.png",
    tagChannelIcon:"/assets/images/createPost/tagChannelIcon.png",
    tagPeopleIcon:"/assets/images/createPost/tagPeople.png",
    hashTagIcon:"/assets/images/createPost/hashTagIcon.png",
    topicSearchIcon:"/assets/images/createPost/topicSearchIcon.png",
    textIcon:"/assets/images/createPost/textIcon.png",
    showIcon:"/assets/images/createPost/showIcon.png",
    musicImg1:"/assets/images/createPost/musicImg1.png",
    musicImg2:"/assets/images/createPost/musicImg2.png",
    // test video 
    videoSrc:"/assets/video/test-video.mp4",
}

export default Images